---
- hosts: 172.31.35.140
  become: yes
  tasks: 
  - name: i want to execute linux command directly
    command: hostname -f
    register: myresult

  - name: i want to debug
    debug:
       msg: "{{myresult}}"
