---
- name: give the  tomcat group ownership
  file: 
     path: /opt/tomcat
     state: directory
     group: tomcat
     recurse: yes

- name: give the tomcat read access to the conf directory
  file:
     path: /opt/tomcat/conf
     state: directory 
     mode: g+r
     rescurse: yes
     
- name: give the tomcat execute accessnto the conf directory
  file:
     path: /opt/tomcat/conf
     state: directory 
     mode: g+x
     
- name: make the tomcat user the owner of the webapps
  file:
     path: /opt/tomcat/webapps/
     state: directory 
     owner: tomcat
     rescurse: yes

- name: make the tomcat user the owner of the works
  file:
    path: /opt/tomcat/works/
    state: directory 
    owner: tomcat
    rescurse: yes
  
- name: make the tomcat user the owner of the temp
  file:
    path: /opt/tomcat/temp/
    state: directory 
    owner: tomcat
    rescurse: yes
  
- name: make the tomcat user the owner of the logs 
  file:
    path: /opt/tomcat/logs/
    state: directory 
    owner: tomcat
    rescurse: yes
      
     
     
  
     
